version: "3.9"

services:
  notifications-api:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.api
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DB_HOST=notifications-db
      - DB_PORT=5432
      - DB_NAME=notifications
      - DB_USER=notifications
      - DB_PASSWORD=notifications
    ports:
      - "8000:8000"
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      notifications-db-init:
        condition: service_completed_successfully

  notifications-worker:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.worker
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DB_HOST=notifications-db
      - DB_PORT=5432
      - DB_NAME=notifications
      - DB_USER=notifications
      - DB_PASSWORD=notifications
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      notifications-db-init:
        condition: service_completed_successfully

  notifications-db:
    image: postgres:16
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: notifications
      POSTGRES_PASSWORD: notifications
    ports:
      - "5433:5432"
    volumes:
      - notifications-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U notifications -d notifications" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  campaign-scheduler:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.api
    command: [ "python", "-m", "notifications.campaign_scheduler.main" ]
    depends_on:
      - notifications-api
    environment:
      - DB_HOST=notifications-db
      - DB_PORT=5432
      - DB_NAME=notifications
      - DB_USER=notifications
      - DB_PASSWORD=notifications
      - API_BASE_URL=http://notifications-api:8000
      - SCHEDULER_POLL_INTERVAL_SECONDS=60
    restart: unless-stopped

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Листенеры
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

      # Настройки для single-node (репликация 1)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # Хранилище логов KRaft
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

      # Любой постоянный Cluster ID
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  kafka-init:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.api  # тот же образ, что и для API
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    command: [ "python", "-m", "notifications.kafka_init" ]
    restart: "no"

  notifications-db-init:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.api
    depends_on:
      notifications-db:
        condition: service_healthy
    environment:
      - DB_HOST=notifications-db
      - DB_PORT=5432
      - DB_NAME=notifications
      - DB_USER=notifications
      - DB_PASSWORD=notifications
    command: ["python", "-m", "notifications.db_init" ]
    restart: "no"

  notifications-worker-tests:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.tests
    working_dir: /app
    command: ["pytest", "-vv", "--log-cli-level=INFO", "src/tests/worker"]
    environment:
      PYTHONPATH: "/app:/app/src"

  notifications-api-tests:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.tests
    working_dir: /app
    command: [ "pytest",  "-vv", "--log-cli-level=INFO", "src/tests/api" ]
    environment:
      PYTHONPATH: "/app:/app/src"

  notifications-campaign-scheduler-tests:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.tests
    working_dir: /app
    command: [ "pytest",  "-vv", "--log-cli-level=INFO", "src/tests/campaign_scheduler" ]
    environment:
      PYTHONPATH: "/app:/app/src"

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP server
    environment:
      MP_SMTP_BIND_ADDR: "0.0.0.0:1025"
      MP_UI_BIND_ADDR: "0.0.0.0:8025"

volumes:
  notifications-db-data: